// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNB6thNZaYa1pE-yRGwTlL8sz4YKR55lU',
    appId: '1:615559293690:web:32b980619870e50a7ab743',
    messagingSenderId: '615559293690',
    projectId: 'auth-demo-77359',
    authDomain: 'auth-demo-77359.firebaseapp.com',
    storageBucket: 'auth-demo-77359.appspot.com',
    measurementId: 'G-EKZCTQ8VS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBooLmv4SKCPXgi7-AjDmAsOMan6UFv-L8',
    appId: '1:615559293690:android:b7cb3457ee86d3f37ab743',
    messagingSenderId: '615559293690',
    projectId: 'auth-demo-77359',
    storageBucket: 'auth-demo-77359.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7NcYj39Y3sQBoKWbzF3J_NZV9htrcZJo',
    appId: '1:615559293690:ios:2ab1f44a21650d417ab743',
    messagingSenderId: '615559293690',
    projectId: 'auth-demo-77359',
    storageBucket: 'auth-demo-77359.appspot.com',
    iosClientId: '615559293690-e6q08528qbn5btq2mfqlmm0nidkaava8.apps.googleusercontent.com',
    iosBundleId: 'in.levitatestudios.dummy.practiceAppp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7NcYj39Y3sQBoKWbzF3J_NZV9htrcZJo',
    appId: '1:615559293690:ios:dfc72f4b8bdf8cdf7ab743',
    messagingSenderId: '615559293690',
    projectId: 'auth-demo-77359',
    storageBucket: 'auth-demo-77359.appspot.com',
    iosClientId: '615559293690-j8ousj1hl1ib95u0cuj2imq8pp3ghnbh.apps.googleusercontent.com',
    iosBundleId: 'in.levitatestudios.dummy.practiceAppp.RunnerTests',
  );
}
